### ISSUE TITLE
Spilo does not build due to postGIS 2.5 dependensy issue

### ISSUE THREAD

**Issue by bas-velthuizen** [zalando/spilo#368] opened 2019-10-21 12:48 UTC
I'm trying to build the docker image for the postgres-appliance, as documented in the readme, but the build fails with the following error:

"postgresql-11-postgis-2.5 : Depends: libgeos-c1v5 (>= 3.7.0) but 3.6.2-1build2 is to be installed"

This seems to be caused by the fact that libgeos-c1v5 version 3.7.0 is not supported by Ubuntu 18.40

This issue is present in tag 1.6-p1

How can I fix this?

**Comment by CyberDem0n** [comment] 2019-10-21 12:52
Hi @bas-velthuizen,

The issue is already [reported](https://www.postgresql.org/message-id/6fedbdeaac774e9d910b8a8edb03b4bd%40kosc-telecom.fr) to pgsql-bugs and I expect that it will be fixed soon.

**Comment by bas-velthuizen** [comment] 2019-10-21 12:55
Hi @CyberDem0n, 

Thanks for the quick response.
Is there any instant patch I could use in the mean time? Or is just removing PostGIS from the Dockerfile the only current way?

**Comment by bas-velthuizen** [comment] 2019-10-22 11:50
Looking at the reported issue you mentioned, this morning I noticed [this reply](https://www.postgresql.org/message-id/3ff654f3ff014a0bbe6104a266d66d68%40kosc-telecom.fr), and indeed, the build worked for PostgreSQL version 10 and 11.

Isn't it dangerous to be so dependent on changes in the outer world? It makes the build of the image very fragile and not reproducible.

**Comment by CyberDem0n** [comment] 2019-10-22 12:05
Pinning a version for any single package sounds like too much work...

**Closed** 2019-12-11 13:00 UTC
