### ISSUE TITLE
spilo-2.1-p5 build raising error : is protobuf related ?

### ISSUE THREAD

**Issue by veragini** [zalando/spilo#738] opened 2022-06-09 01:50 UTC
G'day you all,

Have one of you faced this while building up spilo-2.1-p5 docker image from its source?

Part of the error:

```
 => ERROR [builder-false 7/8] RUN export DEBIAN_FRONTEND=noninteractive     && set -ex     && BUILD_PACKAGES="python3-pip python3-wheel python3-dev git patchutils binutils"     && apt-get update     && apt-cache depends patroni             243.7s
------
```

```
**#21 243.7 protobuf requires Python '>=3.7' but the running Python is 3.6.9**
------
executor failed running [/bin/sh -c export DEBIAN_FRONTEND=noninteractive     && set -ex     && BUILD_PACKAGES="python3-pip python3-wheel python3-dev git patchutils binutils"     && apt-get update     && apt-cache depends patroni             | sed -n -e 's/.* Depends: \(python3-.\+\)$/\1/p'             | grep -Ev '^python3-(sphinx|etcd|consul|kazoo|kubernetes)'             | xargs apt-get install -y ${BUILD_PACKAGES}                         python3-pystache python3-requests     && pip3 install setuptools     && if [ "$DEMO" != "true" ]; then         EXTRAS=",etcd,consul,zookeeper,aws"         && apt-get install -y python3-etcd python3-consul python3-kazoo python3-meld3                         python3-boto python3-gevent python3-greenlet python3-cachetools                         python3-rsa python3-pyasn1-modules python3-swiftclient python3-cffi         && find /usr/share/python-babel-localedata/locale-data -type f ! -name 'en_US*.dat' -delete         && pip3 install filechunkio wal-e[aws,google,swift]==$WALE_VERSION google-crc32c==1.1.2                 'git+https://github.com/zalando/pg_view.git@master#egg=pg-view'         && curl -sL https://github.com/CyberDem0n/wal-e/commit/dad4d53969b93c56f1eaa5243ffa8e9051fd7eb7.diff                 | patch -d /usr/local/lib/python3.6/dist-packages/wal_e -p2         && curl -sL https://github.com/CyberDem0n/wal-e/commit/0309317d33d252fcd968b3eb97313a9fdf022c65.diff                 | patch -d /usr/local/lib/python3.6/dist-packages/wal_e -p2         && curl -sL https://github.com/wal-e/wal-e/commit/485d834a18c9b0d97115d95f89e16bdc564e9a18.diff                 | patch -d /usr/local/lib/python3.6/dist-packages/wal_e -Rp2         && sed -i 's/^\(    for i in range(0,\) num_retries):.*/\1 100):/g'                     /usr/lib/python3/dist-packages/boto/utils.py;     fi     && pip3 install patroni[kubernetes$EXTRAS]==$PATRONIVERSION     && for d in /usr/local/lib/python3.6 /usr/lib/python3; do         cd $d/dist-packages         && find . -type d -name tests | xargs rm -fr         && find . -type f -name 'test_*.py*' -delete;     done     && find . -type f -name 'unittest_*.py*' -delete     && find . -type f -name '*_test.py' -delete     && find . -type f -name '*_test.cpython*.pyc' -delete     && apt-get purge -y ${BUILD_PACKAGES}     && apt-get autoremove -y     && apt-get clean     && rm -rf /var/lib/apt/lists/*             /var/cache/debconf/*             /root/.cache             /usr/share/doc             /usr/share/man             /usr/share/locale/??             /usr/share/locale/??_??             /usr/share/info     && find /var/log -type f -exec truncate --size 0 {} \;]: exit code: 1
```

Thanks

**Comment by veragini** [comment] 2022-06-09 01:55
Perhaps by this ?

https://github.com/protocolbuffers/upb/commit/ef78b6a093f7301c1d1e00aa6308a3016916971d

**Comment by veragini** [comment] 2022-06-09 01:59
It seems the Dockerfile dependencies is pulling protobuf-4.21.0-py2.py3-none-any.whl which has this bug. The https://github.com/protocolbuffers/upb/commit/ef78b6a093f7301c1d1e00aa6308a3016916971d fix will probably come in the 4.21.1 version.

**Comment by veragini** [comment] 2022-06-09 02:01
Two options probably? One upgrade python to 3.7 on Spilo image build which would perhaps require tests etc, or wait for protobuf-4.21.**1** ?

**Comment by CyberDem0n** [comment] 2022-06-09 06:05
We use tags only to mark already built and tested docker images.
Implementing the real reproducible builds would require pinning all possible dependencies, which is too much work.

The issue is already fixed in the master branch: https://github.com/zalando/spilo/pull/732/files#diff-8918d403d0c48088cebb6ed78df4fecd856e211f7522e06ee423383b17bd8453R426
Please just always use the master branch.

**Closed by CyberDem0n** 2022-06-09 06:05 UTC

**Comment by veragini** [comment] 2022-06-09 06:21
Thanks. I worked around just before seen your comment. I will take a look into the above master branch. Cheers

By the way, here is what I did to test, and worked:

From your repo latest not the master - version used 2.1-p5 :

❯ docker image list
REPOSITORY     TAG       IMAGE ID       CREATED          SIZE
spilo-14   2.1-p5    68155a636f8e   49 seconds ago   568MB

I added this after this part: 

# Install patroni and wal-e
ENV PATRONIVERSION=2.1.3
ENV WALE_VERSION=1.1.1
RUN export DEBIAN_FRONTEND=noninteractive \
    && set -ex \
    && BUILD_PACKAGES="python3-pip python3-wheel python3-dev git patchutils binutils" \
    && apt-get update \
\
    **# Workaround**
    _&& apt-get install -y python3-pip \
    && pip3 install --no-cache-dir protobuf==4.21.0rc2 \
    #_

**Comment by veragini** [comment] 2022-06-09 06:26
Another question I observed. in this line here https://github.com/zalando/spilo/blob/master/postgres-appliance/Dockerfile#L287

Shouldn't it be postgresql-${version}-${pkg} instead of postgresql-13-${pkg}  ?

Cheers, Have a great one.

**Comment by CyberDem0n** [comment] 2022-06-09 06:30
> Shouldn't it be postgresql-${version}-${pkg}

It was intentionally set to 13, because there were no packages for the latest version back then.
